### ISSUE TITLE
Easily run specs for all open files?

### ISSUE THREAD

**Issue by kriskhaira** [thoughtbot/vim-rspec#123]
Hi, what's the easiest way to quickly run all specs which are open. For example, if I have 5 files open and 3 of them are in /spec, I'd like to append the filenames for these three files to the spec command.

(Sorry if this is the wrong place for support)

**Comment by gylaz** [comment]
This plugin does not provide that feature. You can probably write a script to do that.

**Comment by kriskhaira** [comment]
No worries. Will work on a script then. Thanks.
