### ISSUE TITLE
Cannot Load spec/controllers/spec ?????

### ISSUE THREAD

**Issue by spinlock99** [thoughtbot/vim-rspec#40]
I have vim-rspec setup and working in "my" projects but I just joined a project that was set up before I go there and I'm getting this strange error when I try to run specs from vim:

```
/Users/spinlock/.rvm/gems/ruby-2.0.0-p247@hoplu/gems/rspec-core-2.14.7/lib/rspec   /core/configuration.rb:896:in `load': cannot load such file -- /Users/spinlock/rails/hoplu/spec/controllers/spec (LoadError)
from /Users/spinlock/.rvm/gems/ruby-2.0.0-p247@hoplu/gems/rspec-core-2.14.7/lib/rspec/core/configuration.rb:896:in `block in load_spec_files'
from /Users/spinlock/.rvm/gems/ruby-2.0.0-p247@hoplu/gems/rspec-core-2.14.7/lib/rspec/core/configuration.rb:896:in `each'
from /Users/spinlock/.rvm/gems/ruby-2.0.0-p247@hoplu/gems/rspec-core-2.14.7/lib/rspec/core/configuration.rb:896:in `load_spec_files'
from /Users/spinlock/.rvm/gems/ruby-2.0.0-p247@hoplu/gems/rspec-core-2.14.7/lib/rspec/core/command_line.rb:22:in `run'
from /Users/spinlock/.rvm/gems/ruby-2.0.0-p247@hoplu/gems/rspec-core-2.14.7/lib/rspec/core/runner.rb:80:in `run'
from /Users/spinlock/.rvm/gems/ruby-2.0.0-p247@hoplu/gems/rspec-core-2.14.7/lib/rspec/core/runner.rb:17:in `block in autorun'
```

Any ideas where to start tracking this down? I can run the specs from the command line but not from withing vim (even with `:!rspec`).

Any help would be appreciated. Thanks!

**Comment by jondavidjohn** [comment]
For anyone that is wanting to run specs from anywhere in your project (not dependant on your `cwd` being in the root, I'm using this with success. Obviously depends on git to get to the project root.

```vimscript
let g:rspec_command = "SPEC="$PWD/{spec}" && (cd `git rev-parse --show-toplevel` && bundle exec rspec "$SPEC" && unset SPEC)"
```

It uses a subshell to move to the appropriate directory before running the specs, this does not effect your `cwd` in vim.

**Comment by phallguy** [comment]
I ended up with this command that searches for the root `spec/` folder and then runs from it's parent.

```
let g:rspec_command = "!clear; ( cd $(find `( SPEC='{spec}'; CP=${SPEC\\%/*}; while [ -n \"$CP\" ] ; do echo $CP; CP=${CP\\%/*}; done; echo / ) ` -mindepth 1 -maxdepth 1 -type d -name spec)/..; bin/rspec {spec})"
```

Credit to 'Zarick Lau' for the parent search method 
http://stackoverflow.com/a/7614803/76456
