### ISSUE TITLE
vim-rspec sending g:rspec_command command to shell rather than vim

### ISSUE THREAD

**Issue by geoffharcourt** [thoughtbot/vim-rspec#61]
I updated `vim-rspec` this weekend (since commit 4c637bd453efcde083a575b0dccd93995b3465bc) and have noticed what seems to be a regression. I am using Dispatch, but the problem can be replicated without Dispatch.

I noticed the issue when I would attempt to run specs, and would get this output

```
Dispatch rspec spec
zsh:1: command not found: Dispatch

shell returned 127

Press ENTER or type command to continue
```

`Dispatch rspec {spec}` (my complete value for `g:rspec_command` was getting returned as an invalid zsh command. If I change my `g:rspec_command` to just `rspec {spec}` (with no exclamation point before the rspec command), then vim-rspec executes the specs.

It looks like vim-rspec is just passing whatever `g:rspec_command` is on to the shell rather than to vim. If I attempt to use the default and not specify a custom command, vim-rspec works as expected. I'm not sure if after this new change to allow simultaneous definitions of `g:rspec_command` and `g:rspec_runner` in 4c637bd453efcde083a575b0dccd93995b3465bc that there's a new configuration that wasn't reflected in the docs or not.

**Comment by kurioscreative** [comment]
Was there ever a resolution of this issue? I can confirm that it is still happening for me on Macvim and iTerm2.
