### ISSUE TITLE
Support for both `bin/rspec` and `rspec` command?

### ISSUE THREAD

**Issue by thewatts** [thoughtbot/vim-rspec#65]
Currently in my Rails projects I use [Spring](https://github.com/rails/spring) for quick loading. Which, with the custom setting, `let g:rspec_command`, that makes it easy.

Ex: `let g:rspec_command = '!bundle exec bin/rspec {spec}'`

However, some of my projects don't use Rails or Spring, which - in that case I need to jump back into my `.vimrc`.

Is there a way to set things up so that I can have the best of both worlds?

---

Side note: This plugin has changed my workflow completely (for the far better) - _thank you_ for your hard work!

**Comment by mecampbellsoup** [comment]
So to be clear, the "best of both worlds" @thewatts requested can be had by `let g:rspec_command = 'rspec {spec}'` and adding `./bin` to one's `PATH` - correct?

**Comment by jondkinney** [comment]
@mecampbellsoup from my testing just now, that is correct. Though I'm using RVM (I'm pretty sure @tpope is not), and I needed to do [this](http://stackoverflow.com/questions/24922259/how-can-i-prepend-a-directory-to-path-using-rvm-on-a-per-project-basis) to get my bin dir in the front of my path: 

1. `brew install direnv`
1. Add `eval $(direnv hook $0)` to the end of my `~/.zshrc` file
1. Create a `.envrc` file in the root of my project with the following content:

    PATH_add bin
