### ISSUE TITLE
Support for Gvim + terminator

### ISSUE THREAD

**Issue by DenniJensen** [thoughtbot/vim-rspec#82]
Hey guys,

I cant find any support for Gvim (vim-gnome) and terminator. Is where any possibility to run test from Gvim in terminator like Mvim on Iterm on OSX?

If yes, can you put it on the readme please.

**Comment by gylaz** [comment]
Right now this plugin only supports OSX terminal and iTerm for GUI vim. We'd welcome a PR for other operating systems and consoles.

**Comment by pedroadame** [comment]
+1 for GVim. Can you @gylaz give a hint on why it doesn't work out of Mac?
