### ISSUE TITLE
Mvim Support: Auto-switch between shell and mvim

### ISSUE THREAD

**Issue by calebmeyer** [thoughtbot/vim-rspec#83]
I don't know if this is even possible, but it would be cool to have.

Currently when I run specs from mvim, they run in a background iterm2. I have a global hotkey for my iterm2, so it's not a huge deal to switch back and forth.

However, it would be nice if mvim could bring the terminal forward, then when you hit enter on the terminal, go back to editing.

**Comment by DavidVII** [comment]
This used to work for me with terminal. I recently updated and now it doesn't.

**Comment by DavidVII** [comment]
Okay, weird. After I commented I ran a spec and it switched just fine.

**Comment by chalmagean** [comment]
That's a nice feature... how can I get that behaviour with iTerm2 (nightly)?

**Comment by gylaz** [comment]
I don't think this should be the concern of this plugin.
