### ISSUE TITLE
Not working with fish shell

### ISSUE THREAD

**Issue by mecampbellsoup** [thoughtbot/vim-rspec#87]
I've switched from zsh recently to fish; here's output when I now try to run my standard `RunNearestSpec()` command (which for me is `<Leader>s`):
```
Error detected while processing function dispatch#tmux#poll..dispatch#complete..<SNR>78_cgetfile:
line   19:
E40: Can't open errorfile /var/folders/zt/sbd8h94n38920pr639nyw0rm0000gn/T/v6AiA2z/18
Error detected while processing function RunNearestSpec:
line    5:
E171: Missing :endif
Press ENTER or type command to continue
```

I can't tell if this is an issue with `vim-rspec` or `vim-dispatch` though... cc @tpope

**Comment by tpope** [comment]
Dispatch definitely doesn't support fish, as Vim itself didn't support fish at the time I wrote it.

**Comment by zorab47** [comment]
Changing the setting of 'shell' back to `/bin/bash` will fix the issue. It causes external commands to launch in a shell other than the default. See [:help 'shell'](http://vimdoc.sourceforge.net/htmldoc/options.html#%27sh%27) for more information
