### ISSUE TITLE
Vim Ginkgo runner

### ISSUE THREAD

**Issue by jaisonerick** [thoughtbot/vim-rspec#99]
Hi,

I'm a daily user of vim-rspec, but recently I needed something like it for Go development. I'm using Ginkgo here, so I took the liberty to create another plugin (https://github.com/jaisonerick/vim-ginkgo-runner) based (TBH, it's more like a copy with some changes) on the vim-rspec code to have a similar environment.

Currently I'm using it just for Ginkgo test suite, but I'm planning to add Go stdlib support too. If there are any plan to evolve the vim-rspec plugin into something more "language agnostic", please, let me know.

Thanks a lot!

**Comment by gylaz** [comment]
Hi @jaisonerick, cool idea! We're keeping `vim-rspec` focused just on RSpec, for simplicity. One of our teammates is currently developing another spec running plugin that would support multiple languages. Have a look at https://github.com/gabebw/vim-spec-runner
